import { test, expect } from "@playwright/test";

test("送信が届かない場合も下書きを保持し、削除をキャンセルできる", async ({ browser, baseURL }) => {
  test.setTimeout(120000);
  const hc = await browser.newContext();
  const pc = await browser.newContext();
  const oc = await browser.newContext();
  const host = await hc.newPage();
  const player = await pc.newPage();
  host.on("dialog", d => void d.accept());
  await host.addInitScript(() => localStorage.setItem("reqgame_ai", JSON.stringify({ provider: "api", apiKey: "", remember: true })));
  await player.route("**/src/net/peer.ts", async route => {
    const response = await route.fetch();
    const source = await response.text();
    expect(source).toContain("this.rawSend(msg);");
    await route.fulfill({ response, body: source.replaceAll("this.rawSend(msg);", 'if (!globalThis.__dropSubmissions || !["ask", "propose"].includes(msg.type)) this.rawSend(msg);') });
  });
  const drop = (value: boolean) => player.evaluate(value => { (globalThis as any).__dropSubmissions = value; }, value);
  try {
    await host.goto(`${baseURL}/#host`);
    await expect(host.locator(".room-code-chip")).toBeVisible({ timeout: 30000 });
    const code = (await host.locator(".room-code-chip").innerText()).replace(/[^A-Z0-9]/g, "");
    await player.goto(`${baseURL}/#${code}`);
    await player.getByLabel("あなたの名前").fill("送信確認係");
    await player.getByRole("button", { name: "参加する", exact: true }).click();
    await expect(player.getByText("ゲーム開始を待っています")).toBeVisible({ timeout: 30000 });
    const other = await oc.newPage();
    await other.goto(`${baseURL}/#${code}`);
    await other.getByLabel("あなたの名前").fill("同席者");
    await other.getByRole("button", { name: "参加する", exact: true }).click();
    await expect(host.locator(".player-tag")).toHaveCount(2, { timeout: 30000 });
    await host.locator('[data-scenario-id="restaurant"]').click();
    await host.getByRole("button", { name: /ゲーム開始/ }).click();
    await host.getByRole("button", { name: /次のフェーズへ/ }).click();
    await player.locator(".tabs").getByRole("button", { name: /要求カード/ }).click();
    await player.getByText("＋ 要求カードを作成", { exact: true }).click();
    const title = player.getByLabel("要求カードのタイトル", { exact: true });
    await title.fill("消えてはいけない要求");
    await drop(true);
    await player.getByRole("button", { name: "提出する", exact: true }).click();
    await expect(title).toBeDisabled();
    await expect(title).toHaveValue("消えてはいけない要求");
    await expect(player.getByText(/送信を確認できませんでした/)).toBeVisible({ timeout: 18000 });
    await expect(title).toBeEnabled();
    await player.reload();
    await player.locator(".tabs").getByRole("button", { name: /要求カード/ }).click();
    await player.getByText("＋ 要求カードを作成", { exact: true }).click();
    await expect(title).toHaveValue("消えてはいけない要求", { timeout: 30000 });
    await player.getByRole("button", { name: "提出する", exact: true }).click();
    await expect(title).toHaveValue("");
    await expect(player.locator(".proposal")).toHaveCount(1);
    player.once("dialog", d => { expect(d.message()).toContain("消えてはいけない要求"); void d.dismiss(); });
    await player.getByRole("button", { name: "削除", exact: true }).click();
    await expect(player.locator(".proposal")).toHaveCount(1);
    player.once("dialog", d => void d.accept());
    await player.getByRole("button", { name: "削除", exact: true }).click();
    await expect(player.locator(".proposal")).toHaveCount(0);
    await player.locator(".tabs").getByRole("button", { name: /ヒアリング/ }).click();
    const question = player.getByLabel("NPCへの質問");
    await question.fill("予約の例外はありますか？");
    await drop(true);
    await player.getByRole("button", { name: "質問する", exact: true }).click();
    await expect(question).toHaveValue("予約の例外はありますか？");
    await expect(player.getByText(/送信を確認できませんでした/)).toBeVisible({ timeout: 18000 });
    await drop(false);
    await player.getByRole("button", { name: "質問する", exact: true }).click();
    await expect(question).toHaveValue("");
    await expect(host.locator(".queue-item")).toHaveCount(1);
  } finally {
    await hc.close();
    await pc.close();
    await oc.close();
  }
});
